[package]
name = "koval"
version = "0.1.0"
edition = "2021"
license-file="LICENSE"
homepage="https://github.com/Dewyer/koval"
repository="https://github.com/Dewyer/koval"

[dependencies]
thiserror = "1.0.30"
