[package]
name = "koval"
version = "0.5.0"
edition = "2021"
license="MIT"
homepage="https://github.com/Dewyer/koval"
repository="https://github.com/Dewyer/koval"
description="A very minimal IOC container"

[dependencies]
thiserror = "1.0.30"
